version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory-service
    ports:
      - 8081:8081
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/inventory_management
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: inventory
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    volumes:
      - ./logs:/app/logs
